name: Reusable Deployment Workflow

on:
  workflow_call:
    inputs:
      tag:
        description: 'The image tag to deploy'
        required: true
        type: string
    secrets:
      BAREMETAL_HOST:
        required: true
      BAREMETAL_USER:
        required: true
      BAREMETAL_SSH_KEY:
        required: true
      BAREMETAL_PORT:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create deployment script
        run: |
          cat << 'EOF' > extract_ecr_to_baremetal.sh
#!/bin/bash
# Extract ECR Docker image to bare metal filesystem

set -e

# Use tag from parameter
IMAGE_TAG="${{ inputs.tag }}"
ECR_IMAGE="764515255972.dkr.ecr.eu-north-1.amazonaws.com/computer-science/floating-point-vectors-inspector:${IMAGE_TAG}"

echo "=== Installing Docker and AWS CLI ==="
sudo apt-get update
sudo apt-get install -y docker.io awscli

echo "=== Setting AWS credentials ==="
export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
export AWS_DEFAULT_REGION="eu-north-1"

echo "=== Logging into ECR ==="
aws ecr get-login-password --region eu-north-1 | sudo docker login --username AWS --password-stdin 764515255972.dkr.ecr.eu-north-1.amazonaws.com

echo "=== Pulling your image: $IMAGE_TAG ==="
sudo docker pull $ECR_IMAGE

echo "=== Creating container (without running) ==="
CONTAINER_ID=$(sudo docker create $ECR_IMAGE)

echo "=== Extracting filesystem to /opt/hpc-app ==="
sudo mkdir -p /opt/hpc-app
sudo docker export $CONTAINER_ID | sudo tar -x -C /opt/hpc-app

echo "=== Cleaning up container ==="
sudo docker rm $CONTAINER_ID

echo "=== Setting up chroot environment ==="
# Mount essential filesystems for chroot
sudo mount --bind /dev /opt/hpc-app/dev
sudo mount --bind /proc /opt/hpc-app/proc
sudo mount --bind /sys /opt/hpc-app/sys
sudo mount --bind /tmp /opt/hpc-app/tmp

echo "=== Creating workspace directory ==="
sudo mkdir -p /opt/hpc-app/workspace

echo "=== Setup complete ==="
echo "You can now enter the environment using: sudo chroot /opt/hpc-app /bin/bash"
EOF
          chmod +x extract_ecr_to_baremetal.sh
          ls -la
          
      - name: Copy deployment script to baremetal host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.BAREMETAL_HOST }}
          username: ${{ secrets.BAREMETAL_USER }}
          key: ${{ secrets.BAREMETAL_SSH_KEY }}
          port: ${{ secrets.BAREMETAL_PORT }}
          source: "extract_ecr_to_baremetal.sh"
          target: "~/"
          overwrite: true

      - name: Run deployment script on baremetal host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BAREMETAL_HOST }}
          username: ${{ secrets.BAREMETAL_USER }}
          key: ${{ secrets.BAREMETAL_SSH_KEY }}
          port: ${{ secrets.BAREMETAL_PORT }}
          script: |
            chmod +x ~/extract_ecr_to_baremetal.sh
            sudo ~/extract_ecr_to_baremetal.sh
