name: Reusable Deployment Workflow

on:
  workflow_call:
    inputs:
      tag:
        description: 'The image tag to deploy'
        required: true
        type: string
      baremetal_host:
        description: 'BAREMETAL_HOST IP address (optional, overrides secret)'
        required: false
        type: string
    secrets:
      BAREMETAL_HOST:
        required: true
      BAREMETAL_USER:
        required: true
      BAREMETAL_SSH_KEY:
        required: true
      BAREMETAL_PORT:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Patch extract_ecr_to_baremetal.sh with tag
        env:
          TAG: ${{ inputs.tag }}
        run: |
          sed -i 's/^IMAGE_TAG=.*/IMAGE_TAG="'$TAG'"/' extract_ecr_to_baremetal.sh
          chmod +x extract_ecr_to_baremetal.sh
          ls -la extract_ecr_to_baremetal.sh

      - name: Copy deployment script to baremetal host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ inputs.baremetal_host != '' && inputs.baremetal_host || secrets.BAREMETAL_HOST }}
          username: ${{ secrets.BAREMETAL_USER }}
          key: ${{ secrets.BAREMETAL_SSH_KEY }}
          port: ${{ secrets.BAREMETAL_PORT }}
          source: "extract_ecr_to_baremetal.sh"
          target: "~/"
          overwrite: true

      - name: Run deployment script on baremetal host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ inputs.baremetal_host != '' && inputs.baremetal_host || secrets.BAREMETAL_HOST }}
          username: ${{ secrets.BAREMETAL_USER }}
          key: ${{ secrets.BAREMETAL_SSH_KEY }}
          port: ${{ secrets.BAREMETAL_PORT }}
          script: |
            chmod +x ~/extract_ecr_to_baremetal.sh
            sudo ~/extract_ecr_to_baremetal.sh
